Repository INF2-2019/aplicacao-web, pull requests merged in 2019-11, with the labels that each got.

#10 Página de manutenção de cursos
  src/_template.html
  src/diario/cursos/index.html
  src/js/diario/cursos/display.js
  src/js/diario/cursos/services/atualizar.js
  src/js/diario/cursos/services/consultar.js
  src/js/diario/cursos/services/deletar.js
  src/js/diario/cursos/services/inserir.js
  src/js/diario/cursos/services/main.js
Labels: enhancement

#21 Listagem dos Professores
  src/diario/professores/index.html
  src/js/diario/professores/consultar.js
  src/js/diario/professores/editar.js
  src/js/diario/professores/inserir.js
  src/js/diario/professores/main.js
Labels: enhancement

#25 Login de aluno
  src/diario/login-aluno.html
  src/js/diario/login-aluno.js
Labels: enhancement

#11 Página de transferência de aluno
  src/diario/transferencia/index.html
  src/js/diario/transferencia/main.js
Labels: enhancement

#14 Página da manutenção de departamentos
  src/diario/departamentos/index.html
  src/js/diario/departamentos/Tabela.js
  src/js/diario/departamentos/consulta.js
  src/js/diario/departamentos/main.js
Labels: enhancement

#22 Relatórios do sistema de biblioteca
  src/biblioteca/relatorios/relatorio1.html
  src/biblioteca/relatorios/relatorio2.html
  src/biblioteca/relatorios/relatorio3.html
  src/biblioteca/relatorios/relatorio4.html
  src/biblioteca/relatorios/relatorio5.html
  src/biblioteca/relatorios/relatorio6.html
  src/css/estilo.css
  src/js/biblioteca/relatorios/consultaAcervo.js
  src/js/biblioteca/relatorios/consultaEmprestimo.js
  src/js/biblioteca/relatorios/consultaReserva.js
  src/js/biblioteca/relatorios/main.js
  src/js/biblioteca/relatorios/pesquisaDescartes.js
  src/js/biblioteca/relatorios/pesquisaEmprestimo.js
  src/js/jquery-3.4.1.js
Labels: enhancement

#13 Listagem do Acervo
  src/biblioteca/acervo/index.html
  src/js/biblioteca/acervo/main.js
  src/js/biblioteca/acervo/parametros.js
Labels: enhancement

#16 Interação do login com back-end
  src/diario/login-professor.html
  src/js/diario/professores/login.js
Labels: enhancement

#45 Login professor +
  src/diario/professores/perfil.html
  src/js/diario/professores/login.js
  src/js/diario/professores/perfil.js
Labels: enhancement

#46 Adicionando credentials ao fetch
  src/js/diario/login-aluno.js
Labels: bug

#42 Página de campi
  src/css/estilo.css
  src/diario/campi/index.html
  src/js/diario/campi/deletar.js
  src/js/diario/campi/editar.js
  src/js/diario/campi/extras.js
  src/js/diario/campi/filtragem.js
  src/js/diario/campi/inserir.js
  src/js/diario/campi/resultado.js
  src/js/diario/campi/tabela.js
Labels: enhancement

#37 Correção de credentials nos fetch's algumas mudanças nas telas do Grupo 7
  src/diario/cursos/index.html
  src/js/biblioteca/relatorios/pesquisaDescartes.js
  src/js/biblioteca/relatorios/pesquisaEmprestimo.js
  src/js/diario/cursos/display.js
  src/js/diario/cursos/services/atualizar.js
  src/js/diario/cursos/services/consultar.js
  src/js/diario/cursos/services/deletar.js
  src/js/diario/cursos/services/inserir.js
  src/js/diario/cursos/services/main.js
Labels: bug, enhancement

#34 Manutenção de etapas - Estilização e Organização
  src/css/estilo.css
  src/diario/etapas/index.html
  src/js/diario/etapas/adiciona.js
  src/js/diario/etapas/conectaServlet.js
  src/js/diario/etapas/consulta.js
  src/js/diario/etapas/deleta.js
  src/js/diario/etapas/edita.js
  src/js/diario/etapas/jquery-3.4.1.js
  src/js/diario/etapas/utils.js
Labels: enhancement

#51 Corrigindo manunt. campi
  src/css/estilo.css
  src/diario/campi/index.html
  src/js/diario/campi/deletar.js
  src/js/diario/campi/editar.js
  src/js/diario/campi/inserir.js
  src/js/diario/campi/tabela.js
Labels: bug

#49 Perfil e Manutenção de alunos
  src/css/estilo.css
  src/diario/alunos/index.html
  src/diario/alunos/perfil.html
  src/js/diario/alunos/deletar.js
  src/js/diario/alunos/editar.js
  src/js/diario/alunos/extras.js
  src/js/diario/alunos/filtragem.js
  src/js/diario/alunos/info.js
  src/js/diario/alunos/inserir.js
  src/js/diario/alunos/perfil.js
  src/js/diario/alunos/resultado.js
  src/js/diario/alunos/tabela.js
Labels: enhancement

#57 Correção modal de deletar
  src/css/estilo.css
  src/diario/alunos/index.html
  src/diario/campi/index.html
Labels: bug

#58 Manutenção de campi e alunos (biblioteca)
  src/biblioteca/alunos/index.html
  src/biblioteca/campi/index.html
  src/js/biblioteca/alunos/deletar.js
  src/js/biblioteca/alunos/editar.js
  src/js/biblioteca/alunos/extras.js
  src/js/biblioteca/alunos/filtragem.js
  src/js/biblioteca/alunos/info.js
  src/js/biblioteca/alunos/inserir.js
  src/js/biblioteca/alunos/resultado.js
  src/js/biblioteca/alunos/tabela.js
  src/js/biblioteca/campi/deletar.js
  src/js/biblioteca/campi/editar.js
  src/js/biblioteca/campi/extras.js
  src/js/biblioteca/campi/filtragem.js
  src/js/biblioteca/campi/inserir.js
  src/js/biblioteca/campi/resultado.js
  src/js/biblioteca/campi/tabela.js
Labels: enhancement

#56 Consertando listagem professores
  src/js/diario/professores/consultar.js
  src/js/diario/professores/editar.js
  src/js/diario/professores/inserir.js
  src/js/diario/professores/main.js
Labels: enhancement

#60 Mais pequenos problemas
  src/diario/professores/index.html
  src/js/diario/professores/inserir.js
  src/js/diario/professores/main.js
  src/js/diario/professores/perfil.js
Labels: enhancement

#61 Relatório 8
  src/css/estilo.css
  src/diario/relatorios/r8.html
  src/js/diario/relatorios/r8.js
Labels: enhancement

#65 Correção na requisição
  src/js/diario/transferencia/main.js
Labels: fix

#62 Melhorias e problemas
  src/biblioteca/acervo/index.html
  src/js/biblioteca/acervo/main.js
  src/js/biblioteca/acervo/parametros.js
Labels: enhancement

#64 Finalização da manutenção de departamentos
  src/diario/departamentos/index.html
  src/diario/index.html
  src/js/diario/departamentos/Selects.js
  src/js/diario/departamentos/Tabela.js
  src/js/diario/departamentos/consulta.js
  src/js/diario/departamentos/deletar.js
  src/js/diario/departamentos/editar.js
  src/js/diario/departamentos/inserir.js
  src/js/diario/departamentos/main.js
Labels: enhancement

#78 Correções em departamentos
  src/diario/departamentos/index.html
  src/js/diario/departamentos/Selects.js
  src/js/diario/departamentos/Tabela.js
  src/js/diario/departamentos/consulta.js
  src/js/diario/departamentos/inserir.js
Labels: fix

#75 Correções na manutenção de etapas
  src/diario/etapas/index.html
  src/js/diario/etapas/adiciona.js
  src/js/diario/etapas/consulta.js
  src/js/diario/etapas/deleta.js
  src/js/diario/etapas/edita.js
  src/js/diario/etapas/utils.js
Labels: enhancement, fix

#80 Correções alunos (biblioteca e diário)
  src/biblioteca/alunos/index.html
  src/diario/alunos/index.html
  src/diario/alunos/perfil.html
  src/js/biblioteca/alunos/editar.js
  src/js/biblioteca/alunos/extras.js
  src/js/biblioteca/alunos/info.js
  src/js/biblioteca/alunos/resultado.js
  src/js/biblioteca/campi/tabela.js
  src/js/diario/alunos/editar.js
  src/js/diario/alunos/extras.js
  src/js/diario/alunos/info.js
  src/js/diario/alunos/perfil.js
  src/js/diario/alunos/resultado.js
  src/js/diario/campi/tabela.js
Labels: fix

#81 Últimos ajustes
  src/diario/professores/index.html
  src/diario/professores/perfil.html
  src/js/biblioteca/acervo/main.js
  src/js/diario/professores/editar.js
  src/js/diario/professores/inserir.js
  src/js/diario/professores/perfil.js
Labels: fix
